name: Build and deploy prenoms API

on:
    push:
        branches:
            - 'main'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Docker build
              run: docker build -t prenoms .
      
            - name: Docker login
              run: docker login -u tommydock21 -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
            - name: Docker tag
              run: docker tag prenoms tommydock21/repo-mlops-gender-prediction:github_${{ github.sha }}
      
            - name: Docker push
              run: docker push tommydock21/repo-mlops-gender-prediction:github_${{ github.sha }}

            - name: Auth GCP gcloud
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

            - name: Set up Cloud SDK
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: Check if Compute Instance 'prenoms-api-tom' exists
              id: check
              run: echo "INSTANCE_EXISTS=$(gcloud compute instances list | grep prenoms-api-tom | wc -l | xargs)" >> "$GITHUB_OUTPUT"
      
            - name: Debug check value
              run: echo 'Existence = ${{ steps.check.outputs.INSTANCE_EXISTS }}'
      
            - name: Create (for the first time) API to GCP Compute Instance
              if: steps.check.outputs.INSTANCE_EXISTS == '0'
              run: |
                gcloud compute instances create-with-container prenoms-api-tom \
                  --container-image tommydock21/repo-mlops-gender-prediction:github_${{ github.sha }} \
                  --tags http-server \
                  --zone us-central1-a \
                  --container-env FLASK_PORT=80
      
            - name: Update API to GCP Compute Instance
              if: steps.check.outputs.INSTANCE_EXISTS != '0'
              run: |
                gcloud compute instances update-container prenoms-api-tom \
                  --container-image tommydock21/repo-mlops-gender-prediction:github_${{ github.sha }} \
                  --zone us-central1-a \
                  --container-env FLASK_PORT=80 