name: Build and deploy prenoms API

on:
    push:
        branches:
            - 'main'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              
            - name: afficher le dossier
              run: ls -l
            
            - name: Afficher la date
              run: date