name: Build and deploy prenoms API

on:
    push:
        branches:
            - 'main'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Docker build
              run: docker build -t prenoms .
      
            - name: Docker login
              run: docker login -u tommydock21 -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
            - name: Docker tag
              run: docker tag prenoms tommydock21/repo-mlops-gender-prediction:latest_github_${{ github.sha }}
      
            - name: Docker push
              run: docker push tommydock21/repo-mlops-gender-prediction:latest_github_${{ github.sha }}


    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: SSH Connect to the VM
              run: gcloud compute ssh --zone "us-central1-c" "gender-predict-tom" --project "ensai-2024" 

            - name: Confirm connexion
              run: pwd