name: Build and deploy prenoms API

on:
    push:
        branches:
            - 'main'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Docker build
              run: docker build -t prenoms .
      
            - name: Docker login
              run: docker login -u tommydock21 -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
            - name: Docker tag
              run: docker tag prenoms tommydock21/repo-mlops-gender-prediction:latest_github_${{ github.sha }}
      
            - name: Docker push
              run: docker push tommydock21/repo-mlops-gender-prediction:latest_github_${{ github.sha }}

            - name: Auth GCP gcloud
              uses: 'google-github-actions/auth@v1'
              with:
                credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

            - name: Set up Cloud SDK
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: SSH Connect to the VM
              run: gcloud compute ssh --zone "us-central1-c" "gender-predict-tom" --project "ensai-2024" 

            - name: Remove the last machine
              run: |
                docker stop $container_id
                docker remove $container_id

            - name: Pull the image
              run: docker pull tommydock21/repo-mlops-gender-prediction:latest_github_${{ github.sha }}

            - name: Run the new version of the app
              run: container_id=$(docker run -d --name test3 -p 80:5000 tommydock21/repo-mlops-gender-prediction:latest_github_${{ github.sha }})

            - name: Just to be sure everything's alright
              run: echo $container=id